# Typical usage:
#   docker compose -p slotopol-pg -f "docker-compose.pg.yml" up -d --build

services:
  slotopol:
    image: schwarzlichtbezirk/slotopol:latest
    container_name: slotopol-srv
    depends_on:
      - database
    ports:
      - 8080:8080
    networks:
      slotopol-net:
        aliases:
          - slotopolhost
    environment:
      SLOTOPOL_DBDRIVER: postgres
      SLOTOPOL_CLUBDSN: postgres://admin:g7Hh23aVb@pghost:5432/slotopol?sslmode=disable
      SLOTOPOL_SPINDSN: postgres://admin:g7Hh23aVb@pghost:5432/slotopol?sslmode=disable
    restart: unless-stopped
    stop_signal: SIGINT
    stop_grace_period: 15s

  database:
    image: postgres:15-alpine
    container_name: slotopol-pg-db
    ports:
      - 5432:5432
    networks:
      slotopol-net:
        aliases:
          - pghost
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: g7Hh23aVb
      POSTGRES_DB: slotopol

networks:
  slotopol-net:
    name: slotopol-net
    external: false
    ipam:
      driver: default
#fly secrets set SLOTOPOL_CLUBDSN=postgres://slotopol_server:8drA63WUPlu2Q0q@tiny-pg-app-asdf-1234.flycast:5432/slotopol_server?sslmode=disable
#fly secrets set SLOTOPOL_SPINDSN=postgres://slotopol_server:8drA63WUPlu2Q0q@tiny-pg-app-asdf-1234.flycast:5432/slotopol_server?sslmode=disable
